import type { Metadata } from "next";
import "./globals.css";
import Header from "@/app/components/header/Header";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const IRANSansXV = localFont({
  src: '../public/fonts/IRANSansXV.woff2',
  display: 'swap',
  variable: '--font-IRANSansXV',

})



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={IRANSansXV.className}>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
